language: python


before_script:
  - docker login -u "${REGISTRY_USERNAME}" -p "${REGISTRY_PASSWORD}"
  - chmod +x build-and-push.sh

jobs:
  include:
    - stage: build-and-push
      script: ./build-and-push.sh
