version: '3.4'
services:
    server:
        build:
          context: .
          dockerfile: ./server/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./server:/server
          - ./server/media:/server/media
        depends_on:
          - db
          - celery
          - redis
        ports:
        - 8000:8000
        environment:
          DEBUG: 'True'
          DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
          BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'
    rabbitmq:
        image: rabbitmq:3.7.5
        hostname: rabbitmq
        ports:
          - 5672:5672
        expose:
          - 5672
        environment:
          RABBITMQ_DEFAULT_USER: 'user'
          RABBITMQ_DEFAULT_PASS: 'password'
          RABBITMQ_DEFAULT_VHOST: 'my_vhost'
    db:
        image: postgres:11.2
        ports:
          - 5432:5432
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres

    redis:
        image: redis:5.0.5
        ports:
          - 6379:6379

    celery:
        build:
          context: ./
          dockerfile: ./server/Dockerfile
        command:  celery -A config worker -B -l info -Q default,celery -s /var/run/celerybeat-schedule
        depends_on:
          - db
          - redis
          - rabbitmq
        volumes:
          - ./server:/server
          - ./server/media:/server/media
        environment:
          DEBUG: 'True'
          DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
          BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'
